version: "3.8"
services:
  web:
    build:
      context: ../../
      dockerfile: Dockerfile
    container_name: web
    env_file:
      - .env
    restart: always
    ports:
      - "8080:8080"
#    networks:
#      - test-docker-network
#networks:
#  test-docker-network:
#    external: true
